#!/bin/sh
### BEGIN INIT INFO
# Provides:          resize2fs_once
# Required-Start: lvm2
# Required-Stop:
# Default-Start: 3
# Default-Stop:
# Short-Description: Resize the /opt filesystem to fill partition
# Description:
### END INIT INFO
. /lib/lsb/init-functions

DISK=/dev/mmcblk0p      # device
OPT_PART=5              # partition number
VGPV=${DISK}${OPT_PART} # volume group physical volume
VGNAME=vg0
LVNAME=opt

_volumes_be_logical(){
  if [ ! -b $VGPV ]; then
    log_daemon_msg "$VGPV not present"
    exit 1
  elif vgdisplay $VGNAME ]; then
    log_daemon_msg "$VGNAME exists"
  fi

  if ! pvcreate -v $VGPV; then
    OPT_ERROR_CODE+="pvcreate $? - "
  fi

  if ! vgcreate --autobackup y --verbose $VGNAME $VGPV; then
    OPT_ERROR_CODE+="vgcreate $? - "
  fi

  if ! lvcreate --autobackup y --verbose --name $LVNAME --extents 92%FREE $VGNAME ; then
    OPT_ERROR_CODE+="lvcreate $? - "
  fi

  if ! mkfs.ext4 -m 12 -E num_backup_sb=2,discard,mmp_update_interval=120 /dev/$VGNAME/$LVNAME; then
    OPT_ERROR_CODE+="mkfs.ext4 $? - "
  else
    echo "/dev/mapper/${VGNAME}-${LVNAME} /opt          ext4    defaults        1 2" >> /etc/fstab
    log_daemon_msg "added /opt to fstab"

  fi

   [ -n "$OPT_ERROR_CODE" ] && log_daemon_msg "Errors during $OPT_ERROR_CODE"

  if [ -d /_opt_prep ]; then
    mv -fv /_opt_prep /opt
  else
    log_daemon_msg "_opt_prep not present"
  fi


    # # ext4 options
    # # -m 12 - reserve 12%
    # # num_backup_sb=2 - create 3 backup superblocks
    # # discard - true
    # # mmp_update_interval=120 - only force write every 120 seconds to increase sdcard lifespan

      # OPT_DEV=$(ls /dev/mapper/*opt) &&
      # resize2fs $OPT_DEV &&
      # update-rc.d resize2fs_once remove &&
      # rm /etc/init.d/resize2fs_once &&
}

case "$1" in
  start)
    log_daemon_msg "Starting resize2fs_once -- "
    log_daemon_msg "Setting up lvm2"
    _volumes_be_logical
    log_end_msg $?
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac
