#!/bin/sh
### BEGIN INIT INFO
# Provides:          resize2fs_once
# Required-Start:
# Required-Stop:
# Default-Start: 3
# Default-Stop:
# Short-Description: Resize the /opt filesystem to fill partition
# Description:
### END INIT INFO
. /lib/lsb/init-functions


DISK=/dev/mmcblk0p

case "$1" in
  start)
    log_daemon_msg "Starting resize2fs_once"
    log_daemon_msg "Setting up lvm2"
    fdisk ${DISK} <<EOF
    o
    n


    $P3_START_SEC
    +${P3_MB}M
    p
    n

    e
    $P4_START_SEC
    +${P4_MB}M
    p
    t
    4
    8e

    p

EOF



if [ -b /dev/mmcblk0p4 ]; then
  pvcreate /dev/mmcblk0p4
  vg create --autobackup y --verbose --name vg0 /dev/sda4
  # TODO change size to be % of total vg size
  lvcreate --autobackup y --verbose --cache --cachemode writethrough --name opt --size 4G vg0
  mkfs.ext4 -m 12 -E num_backup_sb=2,discard,mmp_update_interval=120 /dev/vg0/opt
  # # ext4 options
  # # -m 12 - reserve 12%
  # # num_backup_sb=2 - create 3 backup superblocks
  # # discard - true
  # # mmp_update_interval=120 - only force write every 120 seconds to increase sdcard lifespan
fi
    #ROOT_DEV=`grep -Eo 'root=[[:graph:]]+' /proc/cmdline | cut -d '=' -f 2-` &&


    # OPT_DEV=$(ls /dev/mapper/*opt) &&
    # resize2fs $OPT_DEV &&
    # update-rc.d resize2fs_once remove &&
    # rm /etc/init.d/resize2fs_once &&
    log_end_msg $?
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac
