#!/bin/sh
### BEGIN INIT INFO
# Provides:          resize2fs_once
# Required-Start:
# Required-Stop:
# Default-Start: 3
# Default-Stop:
# Short-Description: Resize the /opt filesystem to fill partition
# Description:
### END INIT INFO
. /lib/lsb/init-functions
case "$1" in
  start)
    log_daemon_msg "Starting resize2fs_once"
    log_daemon_msg "Setting up lvm2"
    #fdisk -Linux LVM 

  # pvcreate /dev/sda4
  # vg create --autobackup y --verbose --name vg0 /dev/sda4
  # lvcreate --autobackup y --verbose --cache --cachemode writethrough --name opt --size 1G vg0
  # mkfs.ext4 -m 12 -E num_backup_sb=2,discard,mmp_update_interval=120 /dev/vg0/opt
  # EOF
  #
  # # ext4 options
  # # -m 12 - reserve 12%
  # # num_backup_sb=2 - create 3 backup superblocks
  # # discard - true
  # # mmp_update_interval=120 - only force write every 120 seconds to increase sdcard lifespan

    #ROOT_DEV=`grep -Eo 'root=[[:graph:]]+' /proc/cmdline | cut -d '=' -f 2-` &&
    OPT_DEV=$(ls /dev/mapper/*opt) &&
    resize2fs $OPT_DEV &&
    update-rc.d resize2fs_once remove &&
    rm /etc/init.d/resize2fs_once &&
    log_end_msg $?
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac
